### ISSUE TITLE
Couldnt find arcface_final.h5 in face recognition folder

### ISSUE THREAD

**Issue by redcodey** [aangfanboy/deepface#3]
> Download a model from face recognition folder, extract it, copy arcface_final.h5 to main_app/python_server/arcface_final.h5

Hi @aangfanboy , I couldnt find the arcface_final.h5 file in the face recognition folder. 
Do we have to build it?

**Comment by aangfanboy** [comment]
Build/make is not needed. After you download the model from [this](https://drive.google.com/file/d/1qUtjhrYDMRqc2lRPNBV1ftkbyIPmTJYp/view) link, rename it as "arcface_final.h5" then copy to deepface/main_app/python_server/arcface_final.h5

**Comment by redcodey** [comment]
ah ok, i see. thank you for the link 👍

**Comment by aangfanboy** [comment]
My pleasure, feel free to re-open the issue if you face any other problems.
